default_volume_directory: '/Users/laurentletourneau-guillon/Dropbox (Personal)/CHUM/RECHERCHE/2020ICHHEMATOMAS/2024_07_getting_all_local_segmentation_data/output/premium_marie_chum/premium_chum_marie_data_cleaned/vols/baseline'
volume_extension: "*.nrrd"
regex_format_volume_load: '(^\\d+.1.*).nrrd$'
regex_format_volume_save: '(^\\d+.1.*).nrrd$'

default_segmentation_directory: '/Users/laurentletourneau-guillon/Dropbox (Personal)/CHUM/RECHERCHE/2020ICHHEMATOMAS/2024_07_getting_all_local_segmentation_data/output/premium_marie_chum/premium_chum_marie_data_cleaned/segms/baseline'
segmentation_extension:  "*.seg.nrrd"
regex_format_segmentation_load:  '.*'
# regex_format_volume_save: "Segmentation(ID_[a-zA-Z0-9]+_instUid_ID_[a-zA-Z0-9]+)*""

annotator_name : 'LLG_premium_review_marie_chum'
annotator_degree : 4 # 0 is default and doest not contain anything,
revision_step : 3 # 0 is default and doest not contain anything,

KEYBOARD_SHORTCUTS:
  - method: "keyboard_toggle_fill"
    shortcut: "e"


OUTLIER_THRESHOLD:
  LOWER_BOUND: -50
  UPPER_BOUND: 150

labels: # !!!make sure that PHE and ICH have no gap between bounds!!!
  - name: "ICH"
    value: 1
    color_r: 255
    color_g: 10
    color_b: 10
    lower_bound_HU: 33
    upper_bound_HU: 90
  - name: "IVH"
    value: 2
    color_r: 230
    color_g: 230
    color_b: 70
    lower_bound_HU: 33
    upper_bound_HU: 90
  - name: "PHE"
    value: 3
    color_r: 11
    color_g: 80
    color_b: 255
    lower_bound_HU: 5
    upper_bound_HU: 33
#  - name: "ventricular_drain"
#    value: 4
#    color_r: 0
#    color_g: 255
#    color_b: 0
#    lower_bound_HU: 90
#    upper_bound_HU: 200
#  - name: "peri_drain_hemorrhage"
#    value: 5
#    color_r: 155
#    color_g: 0
#    color_b: 0
#    lower_bound_HU: 33
#    upper_bound_HU: 90
#  - name: "peri_drain_edema"
#    value: 6
#    color_r: 0
#    color_g: 50
#    color_b: 150
#    lower_bound_HU: 5
#    upper_bound_HU: 33
#  - name: "right_lateral_ventricle"
#    value: 7
#    color_r: 100
#    color_g: 150
#    color_b: 150
#    lower_bound_HU: -20
#    upper_bound_HU: 90
#  - name: "left_lateral_ventricle"
#    value: 8
#    color_r: 100
#    color_g: 100
#    color_b: 150
#    lower_bound_HU: -20
#    upper_bound_HU: 90
#  - name: "third_ventricle"
#    value: 9
#    color_r: 100
#    color_g: 50
#    color_b: 0
#    lower_bound_HU: -20
#    upper_bound_HU: 90
#  - name: "fourth_ventricle"
#    value: 10
#    color_r: 100
#    color_g: 100
#    color_b: 150
#    lower_bound_HU: -20
#    upper_bound_HU: 90
#  - name: "septum_pellucidum"
#    value: 11
#    color_r: 255
#    color_g: 255
#    color_b: 255
#    lower_bound_HU: 0
#    upper_bound_HU: 33